// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aegayadckentahcljxhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlZ2F5YWRja2VudGFoY2xqeGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDA5NzUsImV4cCI6MjA3MTIxNjk3NX0.9iBkfyED3zOP5XWcwcheLgp7Ut7lGUHhLCjBhTDFulU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});